### ISSUE TITLE
Package not installing because of missing requirements.txt

### ISSUE THREAD

**Issue by pbashyal-nmdp** [nmdp-bioinformatics/py-ard#227]
The published package doesn't include `requirements.txt`. Fails when installing with `setup.py`.

**Comment by lgragert** [comment]
Can you test py-ARD with Pandas 2.0?  I had a new rotation student who just started install this version, and already some of my old scripts were throwing up new warnings in their hands since I hadn't set up virtual environments and requirements for everything. https://pandas.pydata.org/docs/dev/whatsnew/v2.0.0.html

**Comment by pbashyal-nmdp** [comment]
It's currently broken with pandas 2.0. When I tried it, they'd changed some APIs that we use and wasn't working. I'd suggest installing pandas with `pip install pandas==1.5.3` if it's possible or better yet, install it in a virtual environment.

**Comment by lgragert** [comment]
Yeah, the new Pandas seems to bust most of my stuff too. The requirements.txt with py-ARD is doing the right thing so I think we're good.

**Comment by pbashyal-nmdp** [comment]
I'll look at updating to pandas 2.0 after the release of 1.0 for py-ard.
