### ISSUE TITLE
Remove asterisk from serology syntax

### ISSUE THREAD

**Issue by rsajulga-nmdp** [nmdp-bioinformatics/py-ard#62]
For example, A*1 should actually be A1

**Comment by pbashyal-nmdp** [comment]
The IMGT page uses a `*` with the Locus name.
![image](https://user-images.githubusercontent.com/8741499/98734581-c8a82b00-2367-11eb-91cb-732b09a846d0.png)

The file has a `*` with the locus name.
https://raw.githubusercontent.com/ANHIG/IMGTHLA/Latest/wmda/rel_dna_ser.txt

```
# file: rel_dna_ser.txt
# date: 2020-10-15
# version: IPD-IMGT/HLA 3.42.0
# origin: http://hla.alleles.org/wmda/rel_dna_ser.txt
# repository: https://raw.githubusercontent.com/ANHIG/IMGTHLA/Latest/wmda/rel_dna_ser.txt
# author: Steven G. E. Marsh (steven.marsh@ucl.ac.uk)
A*;01:01:01:01;1;;;
A*;01:01:01:02N;0;;;
A*;01:01:01:03;1;;;
A*;01:01:01:04;1;;;
A*;01:01:01:05;1;;;
A*;01:01:01:06;1;;;
A*;01:01:01:07;1;;;
A*;01:01:01:08;1;;;
A*;01:01:01:09;1;;;
A*;01:01:01:10;1;;;
A*;01:01:01:11;1;;;
A*;01:01:01:12;1;;;
A*;01:01:01:13;1;;;
A*;01:01:01:14;1;;;
A*;01:01:01:15;1;;;

```

**Comment by rsajulga-nmdp** [comment]
The `*` is probably there for only the allele column. For serology, it should be dropped out. Is this correct, @amadboul-nmdp?

**Comment by amadboul-nmdp** [comment]
@rsajulga-nmdp and @pbashyal-nmdp  The * in the WMDA file indicates that the allele that follows is obtained by DNA typing. For example A*01:01:01:07 has the serological equivalent of A1. this is indicated in the WMDA file as follows:

**A*;01:01:01:07;1;;;**

However, the issue that needs to be fixed in pyard is how the serology typing is input. For example, the input for serology typing should be as follows:

**ard.redux_gl('A1', 'G')**

I believe it is currently as follows:

**ard.redux_gl('A*1', 'G')**

Since a *, in general, indicates a DNA NOT serology typing.

**Comment by pbashyal-nmdp** [comment]
I'm trying to figure out why the Locus name only applies to DNA Allele Name in `A*;01:01:01:01;1;;;`

The documentation for the file says:

![image](https://user-images.githubusercontent.com/8741499/98984593-0633c200-24e8-11eb-8600-551eff1c2fe8.png)

**Comment by pbashyal-nmdp** [comment]
I'm trying to make sure the usage of '*' applies universally, not just to one org.
